POST http://localhost:5000/auth/register
Content-Type: application/json

{
   "Username": "zizi",
  "Password": "zizi",
  "Email": "caca@example.com",
  "Nama_Lengkap": "Test User",
  "Alamat": "123 Test Street"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "Username": "zizi",
  "Password": "zizi"
}


###

GET  http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4Mzg5MzA1LCJleHAiOjE3Mzg0NzU3MDV9.HrBF-NuI0gnipDdOP_qFL0wSrNLRV_7qvUQTzD5EJko


###


GET  http://localhost:5000/api/countuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4OTQ0NjU5LCJleHAiOjE3MzkwMzEwNTl9.COQ4B-_Nai3n4HaPP1V-rJbxJFM1wUvhB_zjutN6XS0


###


GET  http://localhost:5000/api/alluser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4OTkzODQxLCJleHAiOjE3MzkwODAyNDF9.JWEhSUdVJrCwCrmX7LfUcxrLn5TQGCYJMmsk0w77pcw


###
GET  http://localhost:5000/api/buku
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsInJvbGUiOjMsImlhdCI6MTczODE5OTA0NCwiZXhwIjoxNzM4Mjg1NDQ0fQ.BsQDPZWttCEUSLGdB9vRn2r18l0WXrhfw52pXvD6Enk


###

GET http://localhost:5000/api/buku/1111
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4NjMxNDYzLCJleHAiOjE3Mzg3MTc4NjN9.jCjqoWu4jdQL5vQFY907kp2SoRaQD_DH4i-zao6nvgk


###

POST http://localhost:5000/api/buku/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4OTQ0NjU5LCJleHAiOjE3MzkwMzEwNTl9.COQ4B-_Nai3n4HaPP1V-rJbxJFM1wUvhB_zjutN6XS0
Content-Type: application/json

{
  "Judul" : "kiri",
  "Penulis" : "kiri",
  "Penerbit" : "kiri",
  "TahunTerbit" : 2022,
  "Stok" : 11,
  "KategoriID": [1,3]
  
}

###

PUT  http://localhost:5000/api/buku/1125
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsInJvbGUiOjMsImlhdCI6MTczODIxNzYwNywiZXhwIjoxNzM4MzA0MDA3fQ.JKGISwM3gEsVlpEizJBWcGxiBddf6wTWMP3146KSi74
Content-Type: application/json

{
  "Judul" : "kiri",
  "Penulis" : "kiri",
  "Penerbit" : "kiri",
  "TahunTerbit" : 2022,
  "KategoriID": [1,3,4,5]
}

###

GET   http://localhost:5000/api/countborrow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4OTQ0NjU5LCJleHAiOjE3MzkwMzEwNTl9.COQ4B-_Nai3n4HaPP1V-rJbxJFM1wUvhB_zjutN6XS0
###

GET   http://localhost:5000/api/borrow/1114
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4NjMxNDYzLCJleHAiOjE3Mzg3MTc4NjN9.jCjqoWu4jdQL5vQFY907kp2SoRaQD_DH4i-zao6nvgk

###

PUT   http://localhost:5000/api/borrow/1114
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4NjMxNDYzLCJleHAiOjE3Mzg3MTc4NjN9.jCjqoWu4jdQL5vQFY907kp2SoRaQD_DH4i-zao6nvgk
Content-Type: application/json

{
  "PeminjamanID" : 1116
}

###

DELETE http://localhost:5000/api/buku/1112
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4OTAwNzQwLCJleHAiOjE3Mzg5ODcxNDB9.Vtkx-PAiOA9DXiDJ_n0Eb4zy3qgDixb48qXkfINC50c

###

POST http://localhost:5000/auth/kategoribuku
Authorization: Bearer

###

POST http://localhost:5000/auth/kategori_relasi
Authorization: Bearer

###

PUT  http://localhost:5000/api/user/1111
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTExMiwicm9sZSI6MSwiaWF0IjoxNzM4NzU4MDQ0LCJleHAiOjE3Mzg4NDQ0NDR9.pLDQteP5_qZGE2-_H5ef-4E25sGlworY7adpn4hOsnM
Content-Type: application/json

{
  "Username" : "3",
  "Password" : "3",
  "Email" : "3@gmail.com",
  "Nama_Lengkap" : "3",
  "Alamat" : "3",
  "RoleID": 3
}