POST http://localhost:5000/auth/register
Content-Type: application/json

{
   "Username": "zizi",
  "Password": "zizi",
  "Email": "caca@example.com",
  "Nama_Lengkap": "Test User",
  "Alamat": "123 Test Street"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "Username": "zizi",
  "Password": "zizi"
}


###

GET  http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsInJvbGUiOjMsImlhdCI6MTczODAwNTMyOSwiZXhwIjoxNzM4MDkxNzI5fQ.dxLBf-UMRuRcjEZ2g5LAtsvq_Mk_KQWNAZj87x-su3w


###


GET  http://localhost:5000/api/user/33338
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsImlhdCI6MTczNzk3MTk4OSwiZXhwIjoxNzM4MDU4Mzg5fQ.rRCwtjc-Cmfk1rIUO9OVv-FE5af8zSoKK_OgGgVVbgY


###
GET  http://localhost:5000/api/buku
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsInJvbGUiOjMsImlhdCI6MTczODE5OTA0NCwiZXhwIjoxNzM4Mjg1NDQ0fQ.BsQDPZWttCEUSLGdB9vRn2r18l0WXrhfw52pXvD6Enk


###

GET http://localhost:5000/api/buku/1125
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsInJvbGUiOjMsImlhdCI6MTczODIxNzYwNywiZXhwIjoxNzM4MzA0MDA3fQ.JKGISwM3gEsVlpEizJBWcGxiBddf6wTWMP3146KSi74


###

POST http://localhost:5000/api/buku/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsInJvbGUiOjMsImlhdCI6MTczODIxNzYwNywiZXhwIjoxNzM4MzA0MDA3fQ.JKGISwM3gEsVlpEizJBWcGxiBddf6wTWMP3146KSi74
Content-Type: application/json

{
  "Judul" : "kiri",
  "Penulis" : "kiri",
  "Penerbit" : "kiri",
  "TahunTerbit" : 2022,
  "KategoriID": [1,3,4,5]
  
}

###

PUT  http://localhost:5000/api/buku/1125
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsInJvbGUiOjMsImlhdCI6MTczODIxNzYwNywiZXhwIjoxNzM4MzA0MDA3fQ.JKGISwM3gEsVlpEizJBWcGxiBddf6wTWMP3146KSi74
Content-Type: application/json

{
  "Judul" : "kiri",
  "Penulis" : "kiri",
  "Penerbit" : "kiri",
  "TahunTerbit" : 2022,
  "KategoriID": [1,3,4,5]
}

###

DELETE  http://localhost:5000/api/buku/1120
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsInJvbGUiOjMsImlhdCI6MTczODAwNTMyOSwiZXhwIjoxNzM4MDkxNzI5fQ.dxLBf-UMRuRcjEZ2g5LAtsvq_Mk_KQWNAZj87x-su3w

###

DELETE http://localhost:5000/book/buku/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzMzgsImlhdCI6MTczNzI3NDUzOCwiZXhwIjoxNzM3MzYwOTM4fQ.0oyh_wwHaVkYSKRZh1qnr1yy6M-fpnbKjRw3ae7wGLM

###

POST http://localhost:5000/auth/kategoribuku
Authorization: Bearer

###

POST http://localhost:5000/auth/kategori_relasi
Authorization: Bearer

